### ISSUE TITLE
威力同步docker arm 版本1.5.5

### ISSUE THREAD

**Issue by 1990chs** [Jonnyan404/verysync#2]
在docker中安装威力同步，地址如下，安装完为什么是1.5.5版本呢？如何的设置才能为最新2.4.3版本呢？
jonnyan404/verysync:latest
![image](https://user-images.githubusercontent.com/27892759/110243068-cb243580-7f93-11eb-8448-d279bf1969fc.png)

![image](https://user-images.githubusercontent.com/27892759/110243153-23f3ce00-7f94-11eb-809a-49223bcef8a6.png)

**Comment by Jonnyan404** [comment]
> 在docker中安装威力同步，地址如下，安装完为什么是1.5.5版本呢？如何的设置才能为最新2.4.3版本呢？
> jonnyan404/verysync:latest
> ![image](https://user-images.githubusercontent.com/27892759/110243068-cb243580-7f93-11eb-8448-d279bf1969fc.png)
> 
> ![image](https://user-images.githubusercontent.com/27892759/110243153-23f3ce00-7f94-11eb-809a-49223bcef8a6.png)

什么时间下载的?你试试那个带 2.4.3tag的呢

**Comment by Jonnyan404** [comment]
@1990chs 我知道原因了,你这个不是从dockerhub官网拉取的,大概率你配置了第三方源,而第三方源没有从dockerhub实时同步,建议你直接执行 `docker pull jonnyan404/verysync:2.4.3`

**Comment by 1990chs** [comment]
在Portainer中安装的，加上2.4.3这个tag提示没有此tag，我晚上回去截个图



陈庆森
1990chs@163.com
 
发件人： jonny
发送时间： 2021-03-08 10:46
收件人： Jonnyan404/verysync
抄送： 1990chs; Mention
主题： Re: [Jonnyan404/verysync] 威力同步docker arm 版本1.5.5 (#2)
@1990chs 我知道原因了,你这个不是从dockerhub官网拉取的,大概率你配置了第三方源,而第三方源没有从dockerhub实时同步,建议你直接执行 docker pull jonnyan404/verysync:2.4.3

**Comment by Jonnyan404** [comment]
@1990chs 就是我说的,你的源不是官方源,你百度一下解决方案.

**Comment by 1990chs** [comment]
下载出这个是啥意思？网络原因？
![image](https://user-images.githubusercontent.com/27892759/110334057-51587e80-805d-11eb-8241-68743c125e0f.png)

**Comment by 1990chs** [comment]
我添加了一个163和阿里的源，可以下载但是版本好像也不是2.4.3，国内有什么快的源吗？
"registry-mirrors": ["https://registry.docker-cn.com","http://hub-mirror.c.163.com","https://kfwkfulq.mirror.aliyuncs.com"]

**Comment by Jonnyan404** [comment]
@1990chs 用官方源,不要用第三方源

**Comment by 1990chs** [comment]
https://registry.docker-cn.com
这个官方的源访问不了
