### ISSUE TITLE
unraid平台，宿主机重启，同步文件夹设置会丢失

### ISSUE THREAD

**Issue by chqchshj** [Jonnyan404/verysync#3]
unraid平台，宿主机重启，同步文件夹设置会丢失
因为unraid的重启不保留更改设置的机制，导致重启机器后容器配置都丢失了，需要映射微力同步程序的配置文件目录出来才可以持久化，能不能告知配置文件目录在容器内的路径，这样映射出来之后就不会丢失配置了，非常感谢

**Comment by Jonnyan404** [comment]
/data/.config
