### ISSUE TITLE
能不能增加对armv7的支持

### ISSUE THREAD

**Issue by darkelfzdy** [Jonnyan404/verysync#5]
希望建一个微力同步支持armV7的docker版本，我的玩客云不支持arm64

**Comment by Jonnyan404** [comment]
因为有依赖组件不支持其它CPU架构,
后面看看怎么处理,
你可以先用官方的一键脚本安装

**Comment by Jonnyan404** [comment]
> 希望建一个微力同步支持armV7的docker版本，我的玩客云不支持arm64

`docker run --name verysync  -d -p 3000:3000 -p 22037:22037/udp -p 22027:22027/udp  -p 22330:22330 -p 8886:8886 jonnyan404/verysync:test`

请执行这个命令尝试,如果没问题的话,后续都会添加armv7的支持.

**Comment by sonictl** [comment]
我用jonnyan404/verysync:test跑起来了，在armv7上。但是跑得很费劲，因为这个镜像里 /app/docker-entrypoint.sh 第18行有个 fi 写掉了！作者能不能修复之？如果我用修复后的 docker-entrypoint.sh 构建一个新的镜像，启动时貌似没有运行docker-entrypoint.sh

目前的解决方案就是 docker run -it 交互模式进去，改了，手动运行docker-entrypoint.sh。或者以下方式：docker run -it --entrypoint /bin/bash  -v /mnt/sda1/verysync:/data -p 3000:3000 -p 22037:22037/udp -p 22027:22027/udp -p 22330:22330 -e PORT=8886 -p 8886:8886 my_verysync  再手动运行 bash /app/docker-entrypoint.sh

**Comment by Jonnyan404** [comment]
> 我用jonnyan404/verysync:test跑起来了，在armv7上。但是跑得很费劲，因为这个镜像里 /app/docker-entrypoint.sh 第18行有个 fi 写掉了！作者能不能修复之？如果我用修复后的 docker-entrypoint.sh 构建一个新的镜像，启动时貌似没有运行docker-entrypoint.sh
> 
> 目前的解决方案就是 docker run -it 交互模式进去，改了，手动运行docker-entrypoint.sh。或者以下方式：docker run -it --entrypoint /bin/bash -v /mnt/sda1/verysync:/data -p 3000:3000 -p 22037:22037/udp -p 22027:22027/udp -p 22330:22330 -e PORT=8886 -p 8886:8886 my_verysync 再手动运行 bash /app/docker-entrypoint.sh

1. `docker-entrypoint.sh` 文件没问题,并不缺少fi
2. 无法理解你说的 "跑的很费劲" 的意思,如果可以,请说明具体问题或者提交问题日志

**Comment by sonictl** [comment]
嘿，你还不信：

请看：

```bash
# docker images
REPOSITORY            TAG       IMAGE ID       CREATED         SIZE
jonnyan404/verysync   test      4643d251bcc0   6 months ago    43.1MB

# docker run --name test-jonnyan404-verysync -p 3000:3000 -p 22037:22037/udp -p 22027:22027/udp  -p 22330:22330 -p 8886:8886 jonnyan404/verysync:test
+ id -u
+ userid=0
+ '[' 0 '!=' 0 ]
/app/docker-entrypoint.sh: line 18: syntax error: unexpected "else" (expecting "fi")

```

**Comment by Jonnyan404** [comment]
> 嘿，你还不信：
> 
> 请看：
> 
> ```shell
> # docker images
> REPOSITORY            TAG       IMAGE ID       CREATED         SIZE
> jonnyan404/verysync   test      4643d251bcc0   6 months ago    43.1MB
> 
> # docker run --name test-jonnyan404-verysync -p 3000:3000 -p 22037:22037/udp -p 22027:22027/udp  -p 22330:22330 -p 8886:8886 jonnyan404/verysync:test
> + id -u
> + userid=0
> + '[' 0 '!=' 0 ]
> /app/docker-entrypoint.sh: line 18: syntax error: unexpected "else" (expecting "fi")
> ```

重新推送了,你再试试的

**Comment by Jonnyan404** [comment]
已在2.18.x和latest标签中支持
