### ISSUE TITLE
请问，是管生不管养么？

### ISSUE THREAD

**Issue by biubiushaka** [Jonnyan404/verysync#6]
1、官网论坛都是很久以前的帖子才有版主啥的回复，后面的全靠用户自发回复；我看买了Pro的用户发帖也照样是没人理，所以这个付费也只是买功能不买服务呗？
2、3个QQ群，每个我都不同时间申请加入了N次，全没回复。。。
3、所谓的开发者QQ号，申请加好友了同样没通过

**Comment by Jonnyan404** [comment]
1. 你找错地方了
2. 我不是verysync的开发者
3. 没回复也是一种回复
